### ISSUE TITLE
Como eu faço para o programar funcionar?

### ISSUE THREAD

**Issue by stherzada** [Xunjin/Alura-Bank-TS#1]
Olá, boa tarde! Gostaria de saber, como posso fazer para rodar essa api e como funciona, agradecida <3

**Comment by Xunjin** [comment]
Olá tudo bem? Só você clicar [neste link](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by stherzada** [comment]
AH SIMM, entendi muito bem! Muito obrigada
